version: '3'
services:
    app:
        container_name: app-container
        build:
            context: ./docker/
            dockerfile: app.docker
        volumes:
            - ./:/var/www
        tty:
            true
